<?php
    function wbdm_fields_featured_companies() {

	    acf_add_local_field_group( array(
		    'key' => 'group_68448769a108b',
		    'title' => 'Featured companies',
		    'fields' => array(
			    array(
				    'key' => 'field_68448764f0596',
				    'label' => 'Tytul',
				    'name' => 'title',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_68448775f0597',
				    'label' => 'Karuzela loga',
				    'name' => 'logo_carousel',
				    'aria-label' => '',
				    'type' => 'repeater',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'layout' => 'table',
				    'pagination' => 0,
				    'min' => 0,
				    'max' => 0,
				    'collapsed' => '',
				    'button_label' => 'Dodaj wiersz',
				    'rows_per_page' => 20,
				    'sub_fields' => array(
					    array(
						    'key' => 'field_6844878df0598',
						    'label' => 'Logo zdjecie',
						    'name' => 'logo_img',
						    'aria-label' => '',
						    'type' => 'image',
						    'instructions' => '',
						    'required' => 0,
						    'conditional_logic' => 0,
						    'wrapper' => array(
							    'width' => '',
							    'class' => '',
							    'id' => '',
						    ),
						    'return_format' => 'url',
						    'library' => 'all',
						    'min_width' => '',
						    'min_height' => '',
						    'min_size' => '',
						    'max_width' => '',
						    'max_height' => '',
						    'max_size' => '',
						    'mime_types' => '',
						    'preview_size' => 'medium',
						    'parent_repeater' => 'field_68448775f0597',
					    ),
				    ),
			    ),
			    array(
				    'key' => 'field_684487a3f0599',
				    'label' => 'Zdjecie tlo',
				    'name' => 'background_img',
				    'aria-label' => '',
				    'type' => 'image',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'return_format' => 'url',
				    'library' => 'all',
				    'min_width' => '',
				    'min_height' => '',
				    'min_size' => '',
				    'max_width' => '',
				    'max_height' => '',
				    'max_size' => '',
				    'mime_types' => '',
				    'preview_size' => 'medium',
			    ),
		    ),
		    'location' => array(
			    array(
				    array(
					    'param' => 'block',
					    'operator' => '==',
					    'value' => 'wbdm/featured-companies',
				    ),
			    ),
		    ),
		    'menu_order' => 0,
		    'position' => 'normal',
		    'style' => 'default',
		    'label_placement' => 'top',
		    'instruction_placement' => 'label',
		    'hide_on_screen' => '',
		    'active' => true,
		    'description' => '',
		    'show_in_rest' => 0,
	    ) );

    }
    add_action('acf/init', __NAMESPACE__ .'\wbdm_fields_featured_companies');